unitTestMake: quadraticequationspike.c citardauqspike.c
	gcc -Wall -pedantic -o quadeq quadraticequationspike.c -lm -lcunit
	gcc -Wall -pedantic -o ctdqeq citardauqspike.c -lm -lcunit
	
clean:
	rm ./quadeq ./ctdqeq
